### ISSUE TITLE
Fix expanded order details

### ISSUE THREAD

**Issue by simoheinonen** [flydreamers/shipwire-api#19]
> Expand order data in the response, instead of accessing directly via a URL (comma separated list). Valid values are `holds`, `items` , `returns` and `trackings`, `splitOrders`, or simply `all`. See resources `Holds`, `Items`, `Returns`, `Trackings` and `splitOrders` for information on the data model returned by this parameter.

https://www.shipwire.com/w/developers/order/#panel-shipwire0

**Comment by sebathi** [comment]
FIxed and created a new version v0.2.4
