### ISSUE TITLE
Typo in rate example

### ISSUE THREAD

**Issue by rbalik** [flydreamers/shipwire-api#2]
I think I found another typo in the documentation. In the Rate example it looks like you call the config $options, but then you use $config in the call to get a quote.

(Thanks for putting this lib together btw. Definitely making my life easier.)

**Comment by sebathi** [comment]
If uncreate a pull request i will merge and u will contribute to the project!!!

**Comment by rbalik** [comment]
Heh, yeah, I should do that. I'll put something together when I have a minute.
