### ISSUE TITLE
Namespace needs to be specified for lib to work

### ISSUE THREAD

**Issue by rbalik** [flydreamers/shipwire-api#3]
I guess I'm your beta tester :)

This line fails for me:

```
ShipwireConnector::init($KCONFIG['shipwireUser'],
    $KCONFIG['shipwirePass'], $KCONFIG['shipwireMode']);
```

with this error message:

```
[Wed Mar 18 03:17:17.009662 2015] [:error] [pid 18263] [client 10.189.255.252:61272]
 PHP Fatal error:  require(): Failed opening required 'ShipwireConnector.php' (inclu
de_path='.:/usr/share/php:/usr/share/pear:includes/:integrations/:email/:') in /home
/reuben/konekt-rest-api/api.php on line 8
```

I am requiring vendor/autoload above it and other composer imports are working.

**Comment by rbalik** [comment]
Ah, I fixed it by doing `flydreamers\shipwire\ShipwireConnector`
I guess there's a namespace issue, but this workaround is fine for now.

**Comment by sebathi** [comment]
Psr4 namespaces. And composer compliance. If you need something else please tell me
