### ISSUE TITLE
Problem with non-English characters

### ISSUE THREAD

**Issue by rbalik** [flydreamers/shipwire-api#5]
I don't know if this is an issue in this lib or with Shipwire itself, but it has issues when trying to request quotes for addresses that include non-english characters. For example:
Calle 24 Bis No. 48-50 Bogotá, D.C. Colombia

The utf8 á causes a problem. If this is a Shipwire issue, maybe the lib can convert to another character set or something?

**Comment by sebathi** [comment]
Can you try it with curl and check that this library is causing you the troubles? Thx

**Comment by rbalik** [comment]
I used Postman to submit this to ShipWire and it worked:

```
{
    "options" : {
        "currency" : "USD",
        "groupBy" : "all",
        "canSplit" : 1,
        "warehouseArea" : "US"
    },
    "order" : {
        "shipTo" : {
            "address1" : "Calle 24 Bis No. 45-48",
            "country" : "CO",
            "city" : "Bogotá",
            "isCommercial" : 0
        },
    "items" : [
        {
            "sku" : "SIM-N2-2FF3FF",
            "quantity" : 1
        }
        ]
    }
}
```
