### ISSUE TITLE
Dependency "guzzlehttp/guzzle" conflict with aws-sdk

### ISSUE THREAD

**Issue by Justin1989** [flydreamers/shipwire-api#9]
I'm using both aws-sdk and shipwire-api in my project.

shipwire-api requires "guzzlehttp/guzzle": "5.0.3"
but aws-sdk-php "guzzlehttp/guzzle": ">=5.3|~6.0.1|~6.1"

Could you please fix this? thx

**Comment by sebathi** [comment]
Did you try the shipwire api with newer versions of guzzle.
